#name of the workflow/pipeline
name: github action demo pipeline
#trigger event
on:
  push:
    branches:
    - main

jobs:
  demo-job:
   runs-on: ubnutu-latest


  steps:
    -name: checkout code
    uses: actions/checkout@v2

    -name: print message
    run: echo "welcome to gitgub actions"
